### ISSUE TITLE
Сделать заглушку на главной странице, до подключения кошелька

### ISSUE THREAD

**Issue by lappi** [PrimeDealFinance/PrimeDeal-UI#24]

**Comment by lappi** [comment]
![Image](https://github.com/PrimeDealFinance/PrimeDeal-UI/assets/3740390/a1f9eaa3-6362-4d67-a6ba-f7610c9ec6f0)

**Comment by lappi** [comment]
1) Поменять название кнопки CREATE ORDER -> CONNECT WALLET
2) Сделать чтобы работало подключение кошелька

**Comment by VladimirSolo** [comment]
Решил задачу тем что задизейблил кнопку пока не подлкючен кошелек!

**Comment by 0xduda** [comment]
Closes #39
