### ISSUE TITLE
Доделать таблицу, чтобы отображала все параметры. + Валидные лого для актива

### ISSUE THREAD

**Issue by lappi** [PrimeDealFinance/PrimeDeal-UI#27]

**Comment by lappi** [comment]
![Image](https://github.com/PrimeDealFinance/PrimeDeal-UI/assets/3740390/faedf415-6e0d-4f00-9433-e0efe5e5cfb4)

**Comment by lappi** [comment]
Сейчас WBTC/USDC, а на самом деле позиция ETH/USDT

**Comment by lappi** [comment]
Информацию о тикере токена можно получить через функцию name() в контракте ERC-20
Алгоритм,
1) Вызвать на нашем контракте getOpenPositions()
2) взять из. результата адреса токенов A и B
3) Вызвать функцию IERC20.name() у этих контрактов - вернет тикеры (USDT, ETH...)

**Comment by 0xduda** [comment]
Closes #44
