### ISSUE TITLE
Дублирование существующих ордеров

### ISSUE THREAD

**Issue by lappi** [PrimeDealFinance/PrimeDeal-UI#29]

**Comment by lappi** [comment]
Такая же проблема как и в #29

**Comment by VladimirSolo** [comment]
const nextConfig = {
  reactStrictMode: false,
  webpack: (config) => {
    config.externals.push("pino-pretty", "lokijs", "encoding");
    config.resolve.fallback = { fs: false };
    return config;
  },
};

**Comment by 0xduda** [comment]
Closes #44
